// Database for toppings' attributes

export const bread = [
{ id: '1',
  name: 'New York/New Jersey',
  image: 'bread1.jpg',
  text: 'You think you will get a movie about New York, but no.',
  attributes: '&with_keywords=41393',
},
{ id: '2',
  name: 'New England Greek',
  image: 'bread2.jpg',
  text: 'New England style, not in oven but on pan!',
  attributes: '&with_keywords=251940',
},
{ id: '3',
  name: 'Deep dish',
  image: 'bread3.jpg',
  text: 'Here are a few other Windy City classics',
  attributes: '&with_keywords=520',
},
{ id: '4',
  name: 'Multigrain',
  image: 'bread4.jpg',
  text: 'Multigrain and multiverse',
  attributes: '&with_keywords=221309',
},
{ id: '5',
  name: 'Whole wheat',
  image: 'bread5.jpg',
  text: 'Whole wheat for the belly and wholesome for the heart',
  attributes: '&with_keywords=244405',
},
{ id: '6',
  name: 'St. Louis',
  image: 'bread6.jpg',
  text: 'stlouistext',
  attributes: 'stlouisattributes',
},
{ id: '7',
  name: 'Cracker crust',
  image: 'bread7.jpg',
  text: 'These movies will crack you up!',
  attributes: '&with_genres=35',
},
{ id: '8',
  name: 'Flatbread',
  image: 'bread8.jpg',
  text: 'Flat but not necessarily boring. Just the facts',
  attributes: '&with_genres=99',
}
]

export const sauce = [
{ id: '9',
  name: 'Pesto',
  image: 'sauce1.jpg',
  text: 'Like the sauce, these movies are Italian',
  attributes: '&with_keywords=924',
},
{ id: '10',
  name: 'Bechamel',
  image: 'sauce2.jpg',
  text: 'One of French mother sauces, vive la France!',
  attributes: '&with_keywords=4319',
},
{ id: '11',
  name: 'Salsa',
  image: 'sauce3.jpg',
  text: 'The heat! The tension! Spicy mexican standoff',
  attributes: '&with_keywords=1666',
},
{ id: '12',
  name: 'BBQ',
  image: 'sauce4.jpg',
  text: 'Our hero rides off into the sunset, with BBQ sauce on their pizza',
  attributes: '&with_genres=28',
},
{ id: '13',
  name: 'Hummus',
  image: 'sauce5.jpg',
  text: 'HUMM-ours',
  attributes: '&with_genres=35',
},
{ id: '14',
  name: 'Pumpkin',
  image: 'sauce6.jpg',
  text: 'You are weird and we love it!',
  attributes: '&with_genres=9648',
},
{ id: '15',
  name: 'Marinara',
  image: 'sauce7.jpg',
  text: 'Want some safe choices huh?',
  attributes: '&sort_by=vote_average.desc&vote_count.gte=10000',
},
{ id: '16',
  name: 'Tapenade',
  image: 'sauce8.jpg',
  text: 'Tapenade? ... Tagrenade? Grenade!',
  attributes: '&with_genres=10752',
}
]

export const topping = [
{ id: '17',
  name: 'Pepperoni',
  image: 'topping1.jpg',
  text: 'Everybody likes pepperoni!',
  attributes: '&sort_by=popularity.desc',
},
{ id: '18',
  name: 'Mushrooms',
  image: 'topping2.jpg',
  text: 'Explosions with mushroom clouds!',
  attributes: '&with_people=865',
},
{ id: '19',
  name: 'Onions',
  image: 'topping3.jpg',
  text: 'You will be in tears',
  attributes: '&with_keywords=156924',
},
{ id: '20',
  name: 'Sausage',
  image: 'topping4.jpg',
  text: 'Meat is murder. Tasty, tasty murder.',
  attributes: '&with_genres=53',
},
{ id: '21',
  name: 'Bacon',
  image: 'topping5.jpg',
  text: 'What can be more American than bacon?',
  attributes: '&with_keywords=12396',
},
{ id: '22',
  name: 'Extra cheese',
  image: 'topping6.jpg',
  text: 'Extra cheesy movies, coming right up!',
  attributes: '&with_genres=10749',
},
{ id: '23',
  name: 'Black olives',
  image: 'topping7.jpg',
  text: 'Olive... Old-live... Old and still live? Classic movies then',
  attributes: '&with_keywords=11020',
},
{ id: '24',
  name: 'Green peppers',
  image: 'topping8.jpg',
  text: 'greenpeppertext',
  attributes: 'greenpepperattributes',
},
{ id: '25',
  name: 'Pineapple',
  image: 'topping9.jpg',
  text: 'You seem to like a little bit of controversy',
  attributes: '&with_keywords=190804',
},
{ id: '26',
  name: 'Spinach',
  image: 'topping10.jpg',
  text: 'Do you know who also love spinach? Popeye!',
  attributes: '&with_keywords=9860',
},
{ id: '27',
  name: 'Tomatoes',
  image: 'topping11.jpg',
  text: 'Tomatoes or fake blood?',
  attributes: '&with_keywords=11249',
},
{ id: '28',
  name: 'Chicken',
  image: 'topping12.jpg',
  text: 'I hope you are not too chicken for these movies.... Bok Bok.',
  attributes: '&with_genres=27',
},
{ id: '29',
  name: 'Buffalo mozzarella',
  image: 'topping13.jpg',
  text: 'The queen of the Mediterranean cuisine - buffalo mozzarella',
  attributes: '&with_keywords=2853',
},
{ id: '30',
  name: 'Basil',
  image: 'topping14.jpg',
  text: 'Fresh, new movies to keep you up-to-date',
  attributes: '&sort_by=release_date.desc&primary_release_year=2019',
},
{ id: '31',
  name: 'Salami',
  image: 'topping15.jpg',
  text: 'salamitext',
  attributes: 'salamiattributes',
},
{ id: '32',
  name: 'Ham',
  image: 'topping16.jpg',
  text: 'How about some slice of life?',
  attributes: '&with_keywords=9914',
}
]
